CC = gcc
CFLAGS = -ggdb -O0 -Wall


All: 

cd /var/lib/jenkins/workspace/Vms_va/POC/CameraTampering/Linux && $(MAKE)
#cd ../../..
#cd /var/lib/jenkins/workspace/Vms_va/POC/FaceRecognition/Linux && $(MAKE)
#cd ../../..
#cd /var/lib/jenkins/workspace/Vms_va/POC/LPR/Linux && $(MAKE)
#cd ../../..
#cd /var/lib/jenkins/workspace/Vms_va/POC/MotionDetection/Linux && $(MAKE)
#cd ../../..
#cd /var/lib/jenkins/workspace/Vms_va/POC/QueueManagement/Linux && $(MAKE)
#cd ../../..



